export const productData = [
  // Slab
  { name: 'Contempo', category: 'Slab' },
  { name: 'Geneva', category: 'Slab' },
  { name: 'Marseille', category: 'Slab' },
  { name: 'Nova', category: 'Slab' },
  { name: 'Omega', category: 'Slab' },
  { name: 'Roma', category: 'Slab' },
  { name: 'Sussex', category: 'Slab' },
  { name: 'Sydney', category: 'Slab' },
  { name: 'Turin', category: 'Slab' },

  // Shaker
  { name: 'Banff FP', category: 'Shaker' },
  { name: 'Bristol', category: 'Shaker' },
  { name: 'Concord', category: 'Shaker' },
  { name: 'Cypress', category: 'Shaker' },
  { name: 'Harvard', category: 'Shaker' },
  { name: 'Lancaster', category: 'Shaker' },
  { name: 'Lancaster II', category: 'Shaker' },
  { name: 'Lancaster II Beaded', category: 'Shaker' },
  { name: 'Lancaster V Groove', category: 'Shaker' },
  { name: 'Oxford', category: 'Shaker' },
  { name: 'Oxford Wide', category: 'Shaker' },
  { name: 'Parklane', category: 'Shaker' },
  { name: 'Regal', category: 'Shaker' },
  { name: 'Santa Fe', category: 'Shaker' },
  { name: 'Santa V Groove', category: 'Shaker' },
  { name: 'Shaker Florence', category: 'Shaker' },
  { name: 'Slimeline', category: 'Shaker' },
  { name: 'Trillium', category: 'Shaker' },
  { name: 'Whistler', category: 'Shaker' },
  { name: 'York', category: 'Shaker' },

  // Raised Panel
  { name: 'Aspen', category: 'Raised Panel' },
  { name: 'Banff', category: 'Raised Panel' },
  { name: 'Classic', category: 'Raised Panel' },
  { name: 'Elegance', category: 'Raised Panel' },
  { name: 'Glacier', category: 'Raised Panel' },
  { name: 'Kalmar', category: 'Raised Panel' },
  { name: 'Mauka', category: 'Raised Panel' },
  { name: 'Tuscany', category: 'Raised Panel' },
  { name: 'Venice', category: 'Raised Panel' },
  { name: 'Vermont', category: 'Raised Panel' },
  { name: 'Verona', category: 'Raised Panel' },
  { name: 'Verona GE', category: 'Raised Panel' },
  { name: 'Winterset', category: 'Raised Panel' },
];
export const categories = {
  Shaker: [0, 3, 6, 9, 12],
  Slab: [1, 4, 7, 10, 13],
  RaisedPanel: [2, 5, 8, 11, 14],
};
